Vehicle Auction (capstone project)
yuvenalmash/vehicle-auction pull request #1
Opened 2022-11-24 11:39 UTC by yuvenalmash

# Changes include:
- Add two pages i.e home and about
## Home page
- Contains details of the event

## About page
- Contains the program and featured vehicles
### Program
- Contains the schedule of the event 
### Featured vehicle
- The content is dynamic
- Has a popup feature when more details button is clicked

## [Project Link](https://yuvenalmash.github.io/vehicle-auction/)
## [Video Link](https://www.loom.com/share/04ad08f8c3fb47b6b4c4fbf77160c4d9)

2022-11-24 14:19 UTC, Santiago220991 requested changes
Hi @yuvenalmash, 
I'm Santiago your reviewer for this PR :wave: :wave:
 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
:heavy_check_mark: Followed GitHub flow.
:heavy_check_mark: Good PR summary.
:heavy_check_mark: No linter errors.

## Required Changes ♻️
- The presentation video should show all your pages on desktop and mobile versions. Kindly show also the about page. :+1: :smiley: :smiley: 

- The presentation video should contain highlights of a piece of code that you are proud of or you find interesting.

- As a requirement of the project you should create two pages. Main page and About page. Kindly create also the about page. :eyes: :eyes: 
Template design about page:

Desktop
![image](https://user-images.githubusercontent.com/98363075/203797590-6f6ca86e-de17-43b8-8648-ce8bdfb1c49b.png)

Mobile
![image](https://user-images.githubusercontent.com/98363075/203797741-8828dd38-6dd5-4c2b-9fc2-23816e3427e9.png)

- Kindly make sure to add the partners and footer sections to your pages.

Your design 
![image](https://user-images.githubusercontent.com/98363075/203806324-a818ab55-e2e5-4c23-94a6-e719b281135d.png)

Template design
![image](https://user-images.githubusercontent.com/98363075/203806418-402638ea-dcec-4c9e-99b6-1046fc859e04.png)

 
- [OPTIONAL] I think it is a good idea to use arrow functions instead of common functions. Arrow functions are a new and faster way to write functions introduced in ECMA6. :nerd_face: :nerd_face: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-24 14:19 UTC, Santiago220991 commented on index.html
> +    </popup-feature> -->
Please remove the commented code. It makes your project looks messy. :+1: :smiley: :smiley:

2022-11-24 14:19 UTC, Santiago220991 commented on README.md
> +I would like to thank Microverse for the inspiration
Kindly make sure to give credit for the design to Cindy Shin the author of the original design.  :+1: :smiley: :smiley:

2022-11-24 14:19 UTC, Santiago220991 commented on index.html
> +    </popup-menu>
- I think is a good idea to wrap this block of code inside a `header` tag. This is for semantic reasons. :nerd_face: :nerd_face: 

Kindly make sure that your project sticks as much as possible to the Template provided:
- Kindly add the dark bar in the header of your project. :pray: :pray: The objective of this project is to replicate the original design.

Your design
![image](https://user-images.githubusercontent.com/98363075/203800390-23d767cf-2725-4b20-8cb9-a64fc56371fb.png)

Template design
![image](https://user-images.githubusercontent.com/98363075/203800265-270d92bc-9eec-4d54-b96e-5474565ff8d5.png)

- Also please add the other links in your navbar even if you are not going to use them. As I said before the objective is to replicate the original design.

Your design
![image](https://user-images.githubusercontent.com/98363075/203800774-99a5bfeb-65d2-4b8a-81bd-be653aa63fd9.png)

Template design
![image](https://user-images.githubusercontent.com/98363075/203800966-f8bcf5f5-6f7e-4650-b5ef-860ca8aa90d6.png)

- I think it is a good idea to make that the mobile menu covers the page. This is for improving the user's experience.
Your design
![image](https://user-images.githubusercontent.com/98363075/203802499-94c7d33e-c239-4b8d-bb1b-c8aa119eaa63.png)

Design for better user experience
![image](https://user-images.githubusercontent.com/98363075/203803201-63bdf611-bce5-44a8-8926-dce90d1a2e7d.png)

[OPTIONAL] I think it is also a good idea to reduce the size of the hamburger menu button. It will help to improve the user's experience. :eyes: :eyes:

2022-11-24 14:19 UTC, Santiago220991 commented on index.html
> +      <h1>MEGA AUTOMOBILE<br>AUCTION 2022</h1>
The project should contain just one `h1` tag. Kindly replace the other `h1` with `hx` tags. :pray: :pray:

2022-11-24 14:19 UTC, Santiago220991 commented on index.html
> +      </program>
- Kindly make sure that your project sticks as much as possible to the template provided. The template contains in this section 5 cards and your project contains just 4. Kindly please add one more card. :pray: :pray: 

Your design
![image](https://user-images.githubusercontent.com/98363075/203804231-6d1548da-5445-4e5c-9874-a53eb9e454df.png)

Template design
![image](https://user-images.githubusercontent.com/98363075/203804322-56b74eaf-825f-48db-8784-c82b2f2d8f02.png)

- Also please do not forget to add a hover effect. As you can see in the template when you hover over each card a white border appears around the card.

![image](https://user-images.githubusercontent.com/98363075/203804975-4afb4720-60b1-4e00-8592-e4987d40f122.png)

2022-11-24 14:19 UTC, Santiago220991 commented on js/index.js
> +}
Same kindly make sure that your project sticks as much as possible to the template provided. The template in this section contains 6 cards however your project just contains 4. Kindly add 2 more cards. :eyes: :eyes: 
Your project
![image](https://user-images.githubusercontent.com/98363075/203805445-a5fda80a-b598-42fe-9fb6-beb67a0ef1fe.png)

Template design
![image](https://user-images.githubusercontent.com/98363075/203805533-c906a563-ebba-469a-9d0e-3be828891373.png)

2022-11-25 12:13 UTC, Chimwemwe-127001 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

Hi @yuvenalmash,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f313149537762674378457a4d79592f67697068792e676966](https://user-images.githubusercontent.com/52143815/193364479-90018255-ae56-43c7-a947-d5a38187495a.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 12:15 UTC, merged